apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ${{ values.label_name }}-ingress-http
  namespace: ${{ values.label_name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"