
apiVersion: v1
kind: Pod
metadata:
  name: ${{ values.label_name }}-jenkins-build-agent
spec:
  containers:
  - name: k8s-tools
    tty: true
    image: lachlanevenson/k8s-kubectl:v1.15.3
    command: ["/bin/sh"]
    args: ["-c", "cat"]
    workingDir: "/home/jenkins/agent"
    resources:
      requests:
        memory: "256Mi"
        cpu: "0.25"
      limits:
        memory: "512Mi"
        cpu: "1"
  - name: terraform
    image: SECRET.SECRET.io/SECRET/terraform-build:0.14.5
    tty: true
    resources:
      requests:
        memory: "128Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
  - name: ${{ values.label_name }}-builder
    image: SECRET.SECRET.io/${{ values.label_name }}/${{ values.label_name }}-builder:2
    tty: true
    resources:
      requests:
        memory: "512Mi"
        cpu: "1"
      limits:
        memory: "1024Mi"
        cpu: "1"
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: docker-certs
      mountPath: /certs
    - name: docker-socket
      mountPath: /var/run/
  - name: docker
    image: docker:dind
    tty: true
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: /certs
    volumeMounts:
    - name: docker-certs
      mountPath: /certs
    - name: docker-socket
      mountPath: /var/run/
  volumes:
  - name: docker-certs
    emptyDir: {}
  - name: docker-socket
    emptyDir: {}